apiVersion: batch/v1
kind: CronJob
metadata:
  name: drupal-cron
  namespace: drupal
  labels:
    app: drupal
    component: cron
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid  # Prevent overlapping runs
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 1
      activeDeadlineSeconds: 600
      template:
        metadata:
          labels:
            app: drupal
            component: cron
        spec:
          restartPolicy: OnFailure

          securityContext:
            runAsUser: 82
            runAsGroup: 82
            fsGroup: 82

          containers:
            - name: drupal-cron
              image: drupalcsitestacr.azurecr.io/drupal:v1.0.4 # {"$imagepolicy": "flux-system:drupal"}

              resources:
                requests:
                  cpu: "200m"
                  memory: "256Mi"
                limits:
                  cpu: "1000m"
                  memory: "1Gi"

              command:
                - /bin/sh
                - -c
                - |
                  cd /var/www/html
                  ./vendor/bin/drush --quiet cron

              envFrom:
                - secretRef:
                    name: drupal-secrets
                - configMapRef:
                    name: drupal-env

              volumeMounts:
                - name: tmp
                  mountPath: /tmp

          volumes:
            - name: tmp
              emptyDir:
                medium: Memory
                sizeLimit: 256Mi
