apiVersion: v1
kind: Secret
metadata:
  name: drupal-secrets
  namespace: drupal
type: Opaque
stringData:
  # Azure Database for MySQL
  AZURE_MYSQL_PASSWORD: "your-mysql-password"

  # Azure Cache for Redis (Primary Key from Azure Portal)
  AZURE_REDIS_PASSWORD: "your-redis-primary-key"

  # NOTE: No AZURE_STORAGE_ACCOUNT_KEY needed!
  # CSI driver authenticates via Managed Identity at the cluster level.

  # Drupal hash salt (generate with: openssl rand -hex 37)
  DRUPAL_HASH_SALT: "your-74-character-random-hash-salt"

  # Solr authentication (if required)
  SOLR_AUTH_USER: ""
  SOLR_AUTH_PASSWORD: ""
